config/routes.rb
Rails.application.routes.draw do
  get 'new', to: 'games#new', as: :new
  post 'score', to: 'games#score', as: :score
  post 'res_session', to: 'games#res_session'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require 'open-uri'
require 'json'

class GamesController < ApplicationController
  def new
    @letters = ('A'..'Z').to_a.sample(10)
  end

  def test_english
    url = "https://wagon-dictionary.herokuapp.com/#{@word}"
    word_serialized = open(url).read
    result = JSON.parse(word_serialized)
    result['found']
  end

  def score
    @word = params[:word]
    @score = 0
    if @word.split('').all? { |letter| params[:letters].split('').include?(letter.upcase) }
      if test_english
        @answer = "Congratulations! <strong>#{@word.upcase}</strong> is a
          valid English word!".html_safe
        @score += @word.size
        session[:score] += @score
      else
        @answer = "<strong>#{@word.upcase}</strong> doesn't seem to be an
          English word!".html_safe
      end
    else
      @answer = "Sorry but <strong>#{@word.upcase}</strong> can't be built out
        of #{params[:letters].split('').join(', ')}.".html_safe
    end
  end

  def res_session
    session[:score] = 0
    redirect_to new_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<div class="container">
  <h1>New game</h1>

  <% @letters.each do |letter| %>
  <%= letter %>
  <% end %>

  <p>What's the longest word you can find?</p>

  <form action="score" method="post">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <input type="text" name="word" placeholder="Type in your word">
    <input type="hidden" name="letters" value="<%= @letters.join %>">
    <input type="submit" value="Submit">
  </form>
</div>

app/views/games/score.html.erb
<div class="container">

  <body>
    <h1>Result</h1>

    <%= @answer  %>

    <%= "Your score is #{session[:score]}." %>

    <br>
    <br>

    <%= link_to 'Play again', new_path  %>

    <br>
    <br>

    <%= link_to 'Reset session', res_session_path, method: :post  %>
  </body>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LongestWordGame</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>